### ISSUE TITLE
the released type definition file for query builder incorrect

### ISSUE THREAD

**Issue by zijianhuang** [ctstone/azure-search-client#1]
when compiling with Angular CLI, the compiler report errors about this line:
```js
    executeQuery(options?: SearchOptions & DocumentParseOptions): Promise<import("../types/search").SearchResponse<TDocument>>;

```

in node_modules\azure-search-client\dist\indexes\builders\query-builder.d.ts

Removing to offending rubbish resolved the problem.

Now:

```js
    executeQuery(options?: SearchOptions & DocumentParseOptions): Promise<SearchResponse<TDocument>>;
```

**Comment by ctstone** [comment]
Sorry for the late response. Is this still an issue on version 3.x? If so, what version of angular-cli are you using?
