### ISSUE TITLE
make FieldSchema properties nullable?

### ISSUE THREAD

**Issue by chadbr** [ctstone/azure-search-client#3]
Would you mind if I made a pull request to make most of the FieldSchema properties nullable?

Most of them are not required.

Thanks, Chad

**Comment by chadbr** [comment]
oh -- now I'm confused :)

How would I use the azure-search-types with this package? I thought it was all written in typescript already?

**Comment by ctstone** [comment]
There's nothing to do :)

`azure-search-client` automatically imports the types from `azure-search-types` as a dependency in package.json. You're right, it's all written in TypeScript, but I decided to split up the types so that I could use them independently in other projects besides this client.

**Comment by chadbr** [comment]
ah, yea - I see that now... 

I'll have to refresh my memory -- my original code was trying to use `IndexSchema`
/node_modules/azure-search-client/dist/indexes/types/schema.d.ts

Maybe I just confused the types... I'll have to get back to you in the new year :)
